local P = require("md-doc.parser")

describe("parser.parse_yaml", function()
  it("parses simple string key-value pairs", function()
    local vars = P.parse_yaml("title: My Doc\nauthor: Greg")
    eq(vars.title, "My Doc")
    eq(vars.author, "Greg")
  end)

  it("strips surrounding double quotes from values", function()
    local vars = P.parse_yaml('name: "Hello World"')
    eq(vars.name, "Hello World")
  end)

  it("strips surrounding single quotes from values", function()
    local vars = P.parse_yaml("name: 'Hello World'")
    eq(vars.name, "Hello World")
  end)

  it("skips comment lines (# prefix)", function()
    local vars = P.parse_yaml("# this is a comment\ntitle: Test")
    is_nil(vars["# this is a comment"])
    eq(vars.title, "Test")
  end)

  it("skips blank lines", function()
    local vars = P.parse_yaml("\ntitle: Test\n\nauthor: Greg\n")
    eq(vars.title, "Test")
    eq(vars.author, "Greg")
  end)

  it("returns empty table for empty input", function()
    local vars = P.parse_yaml("")
    eq(next(vars), nil)
  end)

  it("handles keys with underscores", function()
    local vars = P.parse_yaml("output_pdf: My Doc.pdf")
    eq(vars.output_pdf, "My Doc.pdf")
  end)

  it("handles keys with hyphens", function()
    local vars = P.parse_yaml("some-key: value")
    eq(vars["some-key"], "value")
  end)

  it("strips trailing spaces from unquoted values", function()
    local vars = P.parse_yaml("title: My Doc   ")
    eq(vars.title, "My Doc")
  end)

  it("silently skips nested/list values (lines starting with spaces)", function()
    local vars = P.parse_yaml("top_key: value\n  nested: ignored\nother: kept")
    eq(vars.top_key, "value")
    eq(vars.other, "kept")
    is_nil(vars.nested)
  end)
end)

describe("parser.strip_frontmatter", function()
  it("splits frontmatter and body", function()
    local result = P.strip_frontmatter("---\ntitle: Test\n---\n# Body")
    eq(result.vars.title, "Test")
    eq(result.body, "# Body")
  end)

  it("returns empty frontmatter when none present", function()
    local result = P.strip_frontmatter("# Just a doc\nno frontmatter")
    eq(result.frontmatter, "")
    eq(result.body, "# Just a doc\nno frontmatter")
    eq(next(result.vars), nil)
  end)

  it("parses multiple frontmatter vars", function()
    local content = "---\ntitle: Proposal\ndate: 2026-06-11\nstatus: draft\n---\nBody text"
    local result = P.strip_frontmatter(content)
    eq(result.vars.title, "Proposal")
    eq(result.vars.date, "2026-06-11")
    eq(result.vars.status, "draft")
    eq(result.body, "Body text")
  end)

  it("returns empty body when nothing after frontmatter", function()
    local result = P.strip_frontmatter("---\ntitle: Test\n---\n")
    eq(result.vars.title, "Test")
    eq(result.body, "")
  end)

  it("returns full content as body when opening --- is not at line 1", function()
    local result = P.strip_frontmatter("# Header\n---\ntitle: Test\n---\n")
    eq(result.frontmatter, "")
    eq(result.body, "# Header\n---\ntitle: Test\n---\n")
  end)
end)
